### PR TITLE
Update AirGradient-DIY.ino

### PR DESCRIPTION
**Pull request by Makr91**
Update Hostname for automatic Dynamic DNS/DHCP address assignment for services like Pi-Hole

### CODE REVIEW

**Comment by geerlingguy** [comment]
Would this make it so you can access the device over `[device-id-here].local` using mDNS?

**Comment by Makr91** [comment]
This doesn't enable MDNS, but that Arduino Library can be added.

If you have a Pi-Hole instance, the device will always show up with it's
programmed Hostname (Usually something like ESP-XXXX) in your DHCP
interface list of clients.

If you're Pi-hole or DNS server does automatically append a search domain
onto your hostnames. Then yes, theoretically this should work to allow you
to access it via a hostname of your choice.




   Mark Gilbert
   Systems Administrator | Cloud Engineer
      Primary mobile: +1-918-917-9378
      FCC Technician License: KF5NTR

**Comment by Makr91** [comment]
I am pseudo-familiar with mDNS, if you want I can add that before we commit this.

**Comment by geerlingguy** [comment]
@Makr91 - No, I'd be okay without it; didn't think about how it would show up in Pi-hole!

**Comment by geerlingguy** [comment]
@Makr91 - One quick question, didn't think about this until just now — if the deviceId is set to empty string, it shouldn't be used for the hostname. Could you do a follow-up PR to put an if around the set hostname bit and make sure the deviceId isn't empty?

**Pull request merged**
